steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/snowarchive-486816/cloud-run-source-deploy/snowarchive
      - .

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - snowarchive
      - --image
      - us-central1-docker.pkg.dev/snowarchive-486816/cloud-run-source-deploy/snowarchive
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - 'us-central1-docker.pkg.dev/snowarchive-486816/cloud-run-source-deploy/snowarchive'
